name = "bseal"
version = "1.0.1"
description = "Generate UUIDs"
licences = ["Apache-2.0"]
repository = { type = "github", user = "julywind168", repo = "bseal" }

# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_erlang = ">= 0.28.0 and < 1.0.0"
gleam_otp = ">= 0.13.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
